server/setup/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, SelectField, SubmitField
from wtforms.validators import InputRequired, Length, Optional


class RoomForm(FlaskForm):
    name = StringField("Name", validators=[InputRequired(), Length(max=64)])
    description = TextAreaField("Description", validators=[Optional(), Length(max=400)])
    submit = SubmitField("Save changes")


class CameraForm(FlaskForm):
    url = StringField("URL", validators=[InputRequired(), Length(max=256)])
    username = StringField("Username", validators=[Optional(), Length(max=64)])
    password = PasswordField("Password", validators=[Optional(), Length(max=128)])
    rooms = SelectField("Installed in", coerce=int)
    submit = SubmitField("Save changes")

server/setup/__init__.py
from flask import Blueprint

bp = Blueprint("setup", __name__)

from server.setup import routes, forms

server/setup/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from server import db
from server.setup import bp
from server.setup.forms import CameraForm, RoomForm
from server.models import Room, Camera, Count


@bp.route("/setup-cameras", methods=["GET", "POST"])
@login_required
def setup_cameras():
    camera_form = CameraForm()
    rooms = Room.query.all()
    camera_form.rooms.choices = [(room.id, room.name) for room in rooms]

    if camera_form.validate_on_submit():
        new_cam = Camera(url=camera_form.url.data, username=camera_form.username.data, password=camera_form.password.data)
        room = Room.query.get(camera_form.rooms.data)
        room.cameras.append(new_cam)
        db.session.commit()
        flash("Added camera with url {}".format(camera_form.url.data))
        return redirect(url_for('setup.setup_cameras'))

    cameras = Camera.query.all()
    return render_template("setup/setup-cameras.html", cameras=cameras, rooms=rooms, camera_form=camera_form, mode="setup")


@bp.route("/setup-cameras/edit-camera/<int:cam_id>", methods=["GET", "POST"])
@login_required
def edit_camera(cam_id):
    cam = Camera.query.get(cam_id)
    camera_data = {"url": cam.url, "username": cam.username, "password": cam.password, "rooms": cam.room_id}
    camera_form = CameraForm(data=camera_data)
    rooms = Room.query.all()
    camera_form.rooms.choices = [(room.id, room.name) for room in rooms]

    if camera_form.validate_on_submit():
        cam.url = camera_form.url.data
        cam.username = camera_form.username.data
        cam.password = camera_form.password.data
        cam.room_id = camera_form.rooms.data
        db.session.commit()
        flash("Updated camera {}".format(cam.id))
        return redirect(url_for('setup.setup_cameras'))

    cameras = Camera.query.all()
    return render_template("setup/setup-cameras.html", cameras=cameras, rooms=rooms, camera_form=camera_form, mode="edit")


@bp.route("/setup-cameras/remove-camera/<int:cam_id>", methods=["GET", "POST"])
@login_required
def remove_camera(cam_id):
    cam = Camera.query.get(cam_id)
    if request.method == "POST":
        db.session.delete(cam)
        db.session.commit()
        flash("Sucessfully removed camera {}".format(cam.id))
        return redirect(url_for('setup.setup_cameras'))
    rooms = Room.query.all()
    cameras = Camera.query.all()
    return render_template("setup/setup-cameras.html", cameras=cameras, rooms=rooms, mode="remove", cam_id=cam.id)


@bp.route("/setup-rooms", methods=["GET", "POST"])
@login_required
def setup_rooms():
    room_form = RoomForm()
    if room_form.validate_on_submit():
        room = Room(name=room_form.name.data, description=room_form.description.data)
        db.session.add(room)
        db.session.commit()
        flash("Added room {}".format(room_form.name.data))
        return redirect(url_for('setup.setup_rooms'))
    rooms = Room.query.all()
    return render_template("setup/setup-rooms.html", rooms=rooms, room_form=room_form, mode="setup")


@bp.route("/setup-rooms/edit-room/<int:room_id>", methods=["GET", "POST"])
@login_required
def edit_room(room_id):
    room = Room.query.get(room_id)
    room_data = {"name": room.name, "description": room.description}
    room_form = RoomForm(data=room_data)
    if room_form.validate_on_submit():
        room.name = room_form.name.data
        room.description = room_form.description.data
        db.session.commit()
        flash("Updated room {} (ID: {})".format(room_form.name.data, room.id))
        return redirect(url_for('setup.setup_rooms'))
    rooms = Room.query.all()
    return render_template("setup/setup-rooms.html", rooms=rooms, room_form=room_form, mode="edit")


@bp.route("/setup-rooms/remove-room/<int:room_id>", methods=["GET", "POST"])
@login_required
def remove_room(room_id):
    room = Room.query.get(room_id)
    if request.method == "POST":
        db.session.delete(room)
        db.session.commit()
        flash("Sucessfully removed {} (ID: {})".format(room.name, room.id))
        return redirect(url_for('setup.setup_rooms'))
    rooms = Room.query.all()
    return render_template("setup/setup-rooms.html", rooms=rooms, mode="remove", room_id=room.id, room_name=room.name)


@bp.route("/setup-general")
@login_required
def setup_general():
    return render_template("setup/setup-general.html")

server/templates/setup/setup-cameras.html
{% extends 'index.html'%}

{% block head %}
<title>People Counter - Camera Setup</title>
{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-centered border bg-light p-3 mt-3 rounded">

        <h4>Cameras</h4>

        {% if rooms %}
            {% if cameras %}
                <div class="card">
                    <ul class="list-group list-group-flush">
                        {% for camera in cameras %}
                            <li href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                Camera {{ camera.id }} - {{ camera.room.name }} - {{ camera.url }}
                                <span>
                                    <a href="{{ url_for('setup.edit_camera', cam_id=camera.id) }}" class="btn btn-secondary py-0 px-2">Edit</a>
                                    <a href="{{ url_for('setup.remove_camera', cam_id=camera.id) }}" class="btn btn-danger py-0 px-2">Remove</a>
                                </span>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% else %}
                <div class="alert alert-info" role="alert">You have not configured any cameras yet.</div>
            {% endif %}

            <!-- Add Button -->
            <button type="button" class="btn btn-primary mt-2" data-toggle="modal" data-target="#add-camera-modal">New camera</button>

            <!-- Add Camera Modal -->
            {% if mode == "setup" or mode == "edit" %}
                <div class="modal fade" id="add-camera-modal" tabindex="-1" role="dialog" aria-labelledby="add-camera-modal-label" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        {% if mode == "setup" %}
                            <h5 class="modal-title" id="add-camera-modal-label">New camera</h5>
                        {% else %}
                            <h5 class="modal-title" id="add-camera-modal-label">Edit camera</h5>
                        {% endif %}
                        <a href="{{ url_for('setup.setup_cameras') }}" class="close" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </a>
                      </div>
                      <div class="modal-body">

                        <form id="camera-form" method="POST" action="" novalidate>
                          {{ camera_form.hidden_tag() }}
                          <div class="form-group">
                            {{ camera_form.url.label }}
                            {{ camera_form.url(class="form-control") }}
                            {% if camera_form.url.errors %}
                                <script>$('#add-camera-modal').modal('show')</script>
                                {% for error in camera_form.url.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            {% endif %}
                          </div>
                          <div class="form-group">
                            {{ camera_form.username.label }}
                            {{ camera_form.username(class="form-control") }}
                            {% if camera_form.username.errors %}
                                <script>$('#add-camera-modal').modal('show')</script>
                                {% for error in camera_form.username.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            {% endif %}
                          </div>
                          <div class="form-group">
                            {{ camera_form.password.label }}
                            {{ camera_form.password(class="form-control") }}
                            {% if camera_form.password.errors %}
                                <script>$('#add-camera-modal').modal('show')</script>
                                {% for error in camera_form.password.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            {% endif %}
                          </div>
                          <div class="form-group">
                            {{ camera_form.rooms.label }}
                            {{ camera_form.rooms(class="form-control") }}
                            {% if camera_form.rooms.errors %}
                                <script>$('#add-camera-modal').modal('show')</script>
                                {% for error in camera_form.rooms.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                            {% endif %}
                          </div>
                        </form>

                      </div>
                      <div class="modal-footer">
                        <a href="{{ url_for('setup.setup_cameras') }}" class="btn btn-secondary">Dismiss</a>
                        {{ camera_form.submit(form="camera-form", class="btn btn-primary") }}
                      </div>
                    </div>
                  </div>
                </div>
            {% endif %}

            <!-- Remove Camera Modal -->
            {% if mode == "remove" %}
                <div class="modal fade" id="remove-camera-modal" tabindex="-1" role="dialog" aria-labelledby="remove-camera-modal-label" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="remove-camera-modal-label">Remove camera</h5>
                        <a href="{{ url_for('setup.setup_cameras') }}" class="close" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </a>
                      </div>
                      <div class="modal-body">
                          Are you sure you want to permanentely remove camera {{ cam_id }}
                          including all counter data acquired by this cameras?
                      </div>
                      <div class="modal-footer">
                        <a href="{{ url_for('setup.setup_cameras') }}" class="btn btn-secondary">No</a>
                        <form method="POST" action="{{ url_for('setup.remove_camera', cam_id=cam_id) }}">
                            <button type="submit" class="btn btn-danger">Yes</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
            {% endif %}

        {% else %} <!-- no rooms exist yet -->
            <div class="alert alert-warning" role="alert">
              Before you can configure a camera you need to add at least one <a href="setup-rooms">room</a>.
            </div>
        {% endif %}

    </div>
  </div>
</div>

{% if mode == "edit" %}
    <script>$('#add-camera-modal').modal('show')</script>
{% elif mode == "remove"%}
    <script>$('#remove-camera-modal').modal('show')</script>
{% endif %}

{% endblock %}

server/templates/setup/setup-general.html
{% extends 'index.html'%}

{% block head %}
<title>People Counter - Setup</title>
{% endblock %}

{% block body %}

{% endblock %}

server/templates/setup/setup-rooms.html
{% extends 'index.html'%}

{% block head %}
<title>People Counter - Room Setup</title>
{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-centered border bg-light p-3 mt-3 rounded">

        <h4>Rooms</h4>

        {% if rooms %}
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% for room in rooms %}
                        <li href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            Room {{ room.id }} - {{ room.name }} - {{ room.description }}
                            <span>
                                <a href="{{ url_for('setup.edit_room', room_id=room.id) }}" class="btn btn-secondary py-0 px-2">Edit</a>
                                <a href="{{ url_for('setup.remove_room', room_id=room.id) }}" class="btn btn-danger py-0 px-2">Remove</a>
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% else %}
            <div class="alert alert-info" role="alert">You have not configured any rooms yet.</div>
        {% endif %}

        <!-- Add Button -->
        <button type="button" class="btn btn-primary mt-2" data-toggle="modal" data-target="#add-room-modal">New room</button>

        <!-- Add Room Modal -->
        {% if mode == "setup" or mode == "edit" %}
            <div class="modal fade" id="add-room-modal" tabindex="-1" role="dialog" aria-labelledby="add-room-modal-label" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                      {% if mode == "setup" %}
                          <h5 class="modal-title" id="add-room-modal-label">New room</h5>
                      {% else %}
                          <h5 class="modal-title" id="add-room-modal-label">Edit room</h5>
                      {% endif %}
                    <a href="{{ url_for('setup.setup_rooms') }}" class="close" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </a>
                  </div>
                  <div class="modal-body">

                    <form id="room-form" method="POST" action="" novalidate>
                      {{ room_form.hidden_tag() }}
                      <div class="form-group">
                        {{ room_form.name.label }}
                        {{ room_form.name(class="form-control") }}
                        {% if room_form.name.errors %}
                            <script>$('#add-room-modal').modal('show')</script>
                            {% for error in room_form.name.errors %}
                                <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                        {% endif %}
                      </div>
                      <div class="form-group">
                        {{ room_form.description.label }}
                        {{ room_form.description(class="form-control") }}
                      </div>
                    </form>

                  </div>
                  <div class="modal-footer">
                    <a href="{{ url_for('setup.setup_rooms') }}" class="btn btn-secondary">Dismiss</a>
                    {{ room_form.submit(form="room-form", class="btn btn-primary") }}
                  </div>
                </div>
              </div>
            </div>
        {% endif %}

        <!-- Remove room Modal -->
        {% if mode == "remove" %}
            <div class="modal fade" id="remove-room-modal" tabindex="-1" role="dialog" aria-labelledby="remove-room-modal-label" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="remove-room-modal-label">Remove room</h5>
                    <a href="{{ url_for('setup.setup_rooms') }}" class="close" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </a>
                  </div>
                  <div class="modal-body">
                      Are you sure you want to permanentely remove {{ room_name }}
                      (ID: {{ room_id }}) including all cameras assigned to this room?
                  </div>
                  <div class="modal-footer">
                    <a href="{{ url_for('setup.setup_rooms') }}" class="btn btn-secondary">No</a>
                    <form method="POST" action="{{ url_for('setup.remove_room', room_id=room_id) }}">
                        <button type="submit" class="btn btn-danger">Yes</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
        {% endif %}
    </div>
  </div>
</div>

{% if mode == "edit" %}
    <script>$('#add-room-modal').modal('show')</script>
{% elif mode == "remove"%}
    <script>$('#remove-room-modal').modal('show')</script>
{% endif %}

{% endblock %}